#!/usr/bin/env python3
"""Assert the published site still ships no third-party code (CON-SEC-003).

CON-SEC-003 asks for the shipped tree and the build tree to be audited separately, because a
single vulnerability count misleads in both directions. On this site the distinction is
unusually clean: everything a visitor downloads is generated by Hugo or vendored into the
repo, and nothing is fetched from another origin. That is a property worth *holding*, not
just observing -- the day a CDN script or a webfont is added, the shipped tree acquires a
supply chain and this check should be what says so.

Run against a built site:  python3 scripts/check-shipped-deps.py [public]
Exit: 0 = still self-contained, 1 = the shipped tree gained an external dependency
"""

import os
import re
import sys

# Namespaces and metadata identifiers, not things the browser fetches.
NOT_A_FETCH = ("schema.org", "www.w3.org", "www.sitemaps.org", "search.yahoo.com",
               "gmpg.org", "purl.org", "ogp.me")

errors, notes = [], []


def main():
    built = sys.argv[1] if len(sys.argv) > 1 else "public"
    if not os.path.isdir(built):
        print(f"error: no built site at {built!r}", file=sys.stderr)
        return 1

    external, pages = {}, 0
    for dp, _, fns in os.walk(built):
        for fn in fns:
            if not fn.endswith(".html"):
                continue
            pages += 1
            html = open(os.path.join(dp, fn), encoding="utf-8", errors="replace").read()
            # Only attributes the browser actually loads from.
            for m in re.finditer(r'(?:src|href)=["\']?(https?://[^"\'> ]+)', html):
                url = m.group(1)
                host = url.split("/")[2] if "//" in url else url
                if any(skip in host for skip in NOT_A_FETCH):
                    continue
                if host.endswith("artbypriti.com"):
                    continue
                external.setdefault(host, os.path.relpath(os.path.join(dp, fn), built))

    if external:
        for host, where in sorted(external.items())[:10]:
            errors.append(f"shipped page {where} loads from an external origin: {host}")
        errors.append("the shipped tree now has a supply chain; audit it as well as the build tree")
    else:
        notes.append(f"{pages} pages checked: no external origins, no runtime dependencies")

    for n in notes:
        print(f"ok:      {n}")
    for e in errors:
        print(f"ERROR:   {e}")
    print(f"\nshipped-tree audit: {len(errors)} error(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
